# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowInitUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(1174, 647)
        mainWindow.setMinimumSize(QtCore.QSize(955, 480))
        mainWindow.setMaximumSize(QtCore.QSize(100000, 100000))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutLeft = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutLeft.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutLeft.setObjectName("verticalLayoutLeft")
        self.labelBq = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelBq.setObjectName("labelBq")
        self.verticalLayoutLeft.addWidget(self.labelBq)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditBq = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditBq.setObjectName("lineEditBq")
        self.horizontalLayout_3.addWidget(self.lineEditBq)
        self.OkPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OkPushButton.setObjectName("OkPushButton")
        self.horizontalLayout_3.addWidget(self.OkPushButton)
        self.verticalLayoutLeft.addLayout(self.horizontalLayout_3)
        self.listBqView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listBqView.setObjectName("listBqView")
        self.verticalLayoutLeft.addWidget(self.listBqView)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 10, 521, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.imagePutTableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.imagePutTableWidget.setObjectName("imagePutTableWidget")
        self.imagePutTableWidget.setColumnCount(0)
        self.imagePutTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.imagePutTableWidget)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(810, 40, 301, 81))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label2.setObjectName("label2")
        self.verticalLayout_2.addWidget(self.label2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ZlkpzPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.ZlkpzPushButton.setObjectName("ZlkpzPushButton")
        self.horizontalLayout.addWidget(self.ZlkpzPushButton)
        self.BqyglPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.BqyglPushButton.setObjectName("BqyglPushButton")
        self.horizontalLayout.addWidget(self.BqyglPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(810, 10, 301, 31))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 10, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(790, 10, 20, 551))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(810, 140, 301, 121))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadImagePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.loadImagePushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.loadImagePushButton.setMaximumSize(QtCore.QSize(100, 25))
        self.loadImagePushButton.setObjectName("loadImagePushButton")
        self.horizontalLayout_2.addWidget(self.loadImagePushButton)
        self.importFolderPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.importFolderPushButton.setMaximumSize(QtCore.QSize(100, 25))
        self.importFolderPushButton.setIconSize(QtCore.QSize(16, 16))
        self.importFolderPushButton.setObjectName("importFolderPushButton")
        self.horizontalLayout_2.addWidget(self.importFolderPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.savePicturePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.savePicturePushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.savePicturePushButton.setMaximumSize(QtCore.QSize(100, 25))
        self.savePicturePushButton.setObjectName("savePicturePushButton")
        self.horizontalLayout_4.addWidget(self.savePicturePushButton)
        self.waiting1 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.waiting1.setMaximumSize(QtCore.QSize(100, 25))
        self.waiting1.setIconSize(QtCore.QSize(16, 16))
        self.waiting1.setObjectName("waiting1")
        self.horizontalLayout_4.addWidget(self.waiting1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1174, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        self.menuabout = QtWidgets.QMenu(self.menubar)
        self.menuabout.setObjectName("menuabout")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionProject = QtWidgets.QAction(mainWindow)
        self.actionProject.setObjectName("actionProject")
        self.actionRegistered = QtWidgets.QAction(mainWindow)
        self.actionRegistered.setObjectName("actionRegistered")
        self.actionOpen = QtWidgets.QAction(mainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionimport_file = QtWidgets.QAction(mainWindow)
        self.actionimport_file.setObjectName("actionimport_file")
        self.actionimport_folder = QtWidgets.QAction(mainWindow)
        self.actionimport_folder.setObjectName("actionimport_folder")
        self.menuImport.addAction(self.actionimport_file)
        self.menuImport.addAction(self.actionimport_folder)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuabout.addAction(self.actionProject)
        self.menuabout.addAction(self.actionRegistered)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "图库"))
        self.labelBq.setText(_translate("mainWindow", "标签"))
        self.lineEditBq.setPlaceholderText(_translate("mainWindow", "筛选标签"))
        self.OkPushButton.setText(_translate("mainWindow", "确定"))
        self.label_3.setText(_translate("mainWindow", "效果图"))
        self.label2.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">管理</span></p></body></html>"))
        self.ZlkpzPushButton.setText(_translate("mainWindow", "资料库配置"))
        self.BqyglPushButton.setText(_translate("mainWindow", "标签库管理"))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">我的归档图库</span></p></body></html>"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">添加</span></p></body></html>"))
        self.loadImagePushButton.setText(_translate("mainWindow", "添加图片"))
        self.importFolderPushButton.setText(_translate("mainWindow", "添加文件夹"))
        self.savePicturePushButton.setText(_translate("mainWindow", "保存"))
        self.waiting1.setText(_translate("mainWindow", "待添加"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuImport.setTitle(_translate("mainWindow", "Import "))
        self.menuabout.setTitle(_translate("mainWindow", "About"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionProject.setText(_translate("mainWindow", "Project"))
        self.actionRegistered.setText(_translate("mainWindow", "Registered"))
        self.actionOpen.setText(_translate("mainWindow", "Open Data"))
        self.actionSave.setText(_translate("mainWindow", "Save Data"))
        self.actionSave.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.actionimport_file.setText(_translate("mainWindow", "import file"))
        self.actionimport_folder.setText(_translate("mainWindow", "import folder"))
